
# This is a basic workflow that is manually triggered
name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version-number:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Which version to label this release as'
        # Default value if no value is explicitly provided
        default: '0.0.0'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: "Build binaries"
        id: "love-build"
        uses: nhartland/love-build@v1-beta2
        with:
          # Name of the application to be built
          app_name: "Chaoshead-${{ github.event.inputs.version-number }}"
          # Version of LÖVE to be used in building the application
          love_version: 11.3
          # Path in the repository to the subdirectory containing `main.lua`. By default the repo root
          # source_dir: # default is ./
          # Directory in the GitHub workspace where the built distributables should be located
          result_dir: "binaries"
      # 32 bits
      - run: mkdir "release"
      - uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ steps.love-build.outputs.win32-filename }}
          pathTarget: release
      - run: mv "release/license.txt" "release/license-love.txt"
      - run: cp "LICENSE.txt" "release/license-Chaoshead.txt"
      - run: cp "credits.txt" "release/credits.txt"
      - uses: actions/upload-artifact@v1
        with:
          name: win32-build
          path: release
